# Generated by Django 4.0.5 on 2022-07-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GbifObservations',
            fields=[
                ('gbifid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('datecreated', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('public', models.BooleanField(default=True)),
                ('acces_rights', models.CharField(max_length=255, null=True)),
                ('rights_holder', models.CharField(max_length=255)),
                ('recorded_by', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('countrycode', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='observations.gbifobserver')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='taxonomy.species')),
            ],
        ),
        migrations.CreateModel(
            name='GbifObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgid', models.IntegerField()),
                ('external_url', models.URLField()),
                ('rights_holder', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='observations.gbifobservations')),
            ],
        ),
        migrations.AddIndex(
            model_name='gbifobservations',
            index=models.Index(fields=['species', 'latitude', 'longitude', 'public'], name='obs_gbifobs_sp_lat_lon_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='gbifobservations',
            index=models.Index(fields=['observer'], name='obs_gbifobs_observer_idx'),
        ),
    ]
