"""Add date to observations

Revision ID: 7f9e82656260
Revises: 4e74c4da2c56
Create Date: 2022-11-21 12:33:01.483826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9e82656260'
down_revision = '4e74c4da2c56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gbif_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer()))
        batch_op.add_column(sa.Column('day', sa.Integer()))

    with op.batch_alter_table('gbif_observations', schema=None) as batch_op:
        batch_op.execute(
            """
            UPDATE gbif_observations 
              SET month = strftime('%m', datecreated),
              day = strftime('%d', datecreated)
              ;""")

        batch_op.alter_column('month',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('day',
                              existing_type=sa.INTEGER(),
                              nullable=False)

        batch_op.create_index('gbif_observations_month_day_latitude_longitutde', [
                              'month', 'day', 'latitude', 'longitude'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('gbif_observations', schema=None) as batch_op:
        batch_op.drop_index('gbif_observations_month_day_latitude_longitutde')
        batch_op.drop_column('day')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
