# Generated by Django 4.0.5 on 2022-07-05 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phylum', models.CharField(max_length=255, unique=True)),
                ('classname', models.CharField(max_length=255, unique=True)),
                ('order', models.CharField(max_length=255, unique=True)),
                ('family', models.CharField(max_length=255, unique=True)),
                ('genus', models.CharField(max_length=255, unique=True)),
                ('species', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('included_in_classifier', models.BooleanField(default=False)),
                ('number_of_observations', models.IntegerField()),
                ('latest_observation', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='species',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('species'), name='species_unique_name'),
        ),
        migrations.AddField(
            model_name='commonnames',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='common_names', to='taxonomy.species'),
        ),
        migrations.AddConstraint(
            model_name='commonnames',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('species'), name='commonnames_unique_name'),
        ),
    ]
