# Generated by Django 4.0.5 on 2022-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='classname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='order',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='phylum',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
