# Generated by Django 4.0.5 on 2022-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_alter_species_classname_alter_species_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
