# Generated by Django 4.0.5 on 2022-07-05 14:22

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_alter_species_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commonnames',
            name='commonnames_unique_name',
        ),
        migrations.RemoveConstraint(
            model_name='species',
            name='species_unique_name',
        ),
        migrations.AddField(
            model_name='commonnames',
            name='language',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='commonnames',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('language'), django.db.models.expressions.F('species'), name='taxonomy_commonnames_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='species',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('species'), name='taxonomy_species_unique_name'),
        ),
    ]
