# Generated by Django 4.0.5 on 2022-07-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_remove_commonnames_commonnames_unique_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='latest_observation',
        ),
    ]
