# Generated by Django 4.0.5 on 2022-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_remove_species_latest_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonnames',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
