# Generated by Django 4.0.5 on 2022-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_alter_commonnames_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commonnames',
            index=models.Index(fields=['species', 'language'], name='taxonomy_cn_species_lang_idx'),
        ),
    ]
