# Generated by Django 4.0.5 on 2022-07-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_remove_commonnames_commonnames_unique_name_and_more'),
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgid', models.IntegerField()),
                ('external_url', models.URLField()),
                ('rights_holder', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('is_thumbnail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GbifObservations',
            fields=[
                ('gbifid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('public', models.BooleanField(default=True)),
                ('acces_rights', models.CharField(max_length=255, null=True)),
                ('rights_holder', models.CharField(max_length=255)),
                ('recorded_by', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('countrycode', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='observations',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='species',
        ),
        migrations.RenameModel(
            old_name='Observer',
            new_name='GbifObserver',
        ),
        migrations.DeleteModel(
            name='ObservationImage',
        ),
        migrations.DeleteModel(
            name='Observations',
        ),
        migrations.AddField(
            model_name='gbifobservations',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='observations.gbifobserver'),
        ),
        migrations.AddField(
            model_name='gbifobservations',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='taxonomy.species'),
        ),
        migrations.AddField(
            model_name='gbifobservationimage',
            name='gbifid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='observations.gbifobservations'),
        ),
    ]
