# Generated by Django 4.0.5 on 2022-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_gbifobservationimage_gbifobservations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gbifobservationimage',
            old_name='gbifid',
            new_name='observation',
        ),
        migrations.AddIndex(
            model_name='gbifobservations',
            index=models.Index(fields=['species', 'latitude', 'longitude', 'public'], name='obs_gbifobs_sp_lat_lon_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='gbifobservations',
            index=models.Index(fields=['observer'], name='obs_gbifobs_observer_idx'),
        ),
    ]
